### ISSUE TITLE
Wrong credits to a patch

### ISSUE THREAD

**Issue by Patola** [snatella/wine-runner-sc#2]
The description of 6.5-alpha says the QueryTraceA comes from @dfkiller
It doesn't. dfkiller is just the messenger. The author of the QueryTraceA patch is @EsdrasTarsis.
Please correct that. @dfkiller can confirm what I am saying.

**Comment by snatella** [comment]
Hello @Patola, sorry it was a misattribution, the release page had the correct names, but once I had pushed (before release) I realised DFKiller was not the source. I don't normally like meddling with git history, but since the patch does not work at all I've pulled the commit and release entirely as is.
